# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.10
fabric_kotlin_version=1.13.0+kotlin.2.1.0

# Mod Properties
mod_version=0.2.0
maven_group=dage.showhelditems
archives_base_name=show-held-items_dev-3

mod_name=Show Held Items
mod_id=show-held-items
mod_description=Shows your Pokémon's held items in the world.
mod_icon=assets/cobblemon_helditems/icon.png
author=joshxviii
repository=https://github.com/joshxviii/cobblemon_helditems
license=CC-BY-NC-4.0

# Dependencies
fabric_version=0.114.0+1.21.1
cobblemon_version=1.6.0+1.21.1